spring.application.name=auth-user-service

server.port=8081

spring.mongodb.uri=mongodb://localhost:27017/booknest_auth_db

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Mail Configuration (Ethereal - For Testing)
spring.mail.host=smtp.ethereal.email
spring.mail.port=587
spring.mail.username=otueq45cqafwkd4y@ethereal.email
spring.mail.password=Hrjz4JBwZ8CaaUCwpu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true