spring.application.name=order-service

server.port=8087

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/booknest_notification_db

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL@gmail.com
spring.mail.password=YOUR_APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Razorpay
razorpay.api.key=rzp_test_SjQeXp4dG1NeqV
razorpay.api.secret=QTAwfSi1cIHTDZIwI7PyPu8W
