spring.application.name=discovery-server
 #Service ka naam

server.port=8761
#Discovery server is port pe chalega

eureka.client.register-with-eureka=false
#Khud ko register nahi karega

eureka.client.fetch-registry=false
#Khud se services fetch nahi karega